name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            shakeelkhuhro/examplecorp-backend:latest
            shakeelkhuhro/examplecorp-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            shakeelkhuhro/examplecorp-frontend:latest
            shakeelkhuhro/examplecorp-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Images
        run: |
          echo "Backend image: shakeelkhuhro/examplecorp-backend:latest"
          echo "Frontend image: shakeelkhuhro/examplecorp-frontend:latest"
          echo "Deployment completed successfully!"